### ISSUE TITLE
The Animations seems not correctly, when importRotationCurve have negative scale?

### ISSUE THREAD

**Issue by stonexing** [Anohros/GrannyConverterLibrary#3]
The normal animation is:
![character](https://user-images.githubusercontent.com/1814765/160552089-c5c1d6ac-feab-4bd9-a74b-667e569bdb39.GIF)
After the conversion, animation is:
![character with animation](https://user-images.githubusercontent.com/1814765/160552217-1f7ff0bd-ad21-404e-9396-97101daf54fa.GIF)

It seems animation is not correct.
How to resolve this issue?

Then I use blender rotate Bone arround Y axis 180 degree.
I got correct animation blew:

![character_fixed_blender](https://user-images.githubusercontent.com/1814765/160624185-c4c28a9e-7f92-42ef-b245-68affbdfe989.gif)

So I think the Transform is error when there has negative scale.
Please fix this issues. Thanks.
my gr2 file is:

[character.gr2.zip](https://github.com/Anohros/GrannyConverterLibrary/files/8368861/character.gr2.zip)

**Comment by stonexing** [comment]
I have success build this project with flowing step:
## Build project step, (构建项目步骤)
1.Clone this project
2.Install VS2017 c++（not test vs2022） 
3.Install CMake latest version and add to system PATH.
4.Turn to project folder ，and Run '''CMake CMakeLists.txt'''
    Make sure there is no cmake error. if has error make sure fbx sdk and devil sdk installed and configration right
    确保cmake执行后错误，若有错误请正确配置fbx和devil的sdk
5.Double click GrannyConverterLibrary.sln then vs2017 will be launch to build this project.
6.Build solution, and wait a monment.
7.After build success, you need add sdk dll to system PATH or copy them to the folder of exe.
8.No step 8.
-------------------------------------------
[character.zip](https://github.com/Anohros/GrannyConverterLibrary/files/8360125/character.zip)

Now, I convert this gr2 then I get an animation out seems not perfect 
When I try to use CviBuddy. the animation out file not perfect same.
What's wrong about my convertion.

**Comment by Anohros** [comment]
Hey I added some changes to the branch [3-bone-transformation](https://github.com/Anohros/GrannyConverterLibrary/tree/3-bone-transformation).

You have to set the just added export option "convertAxis" to "XyZ"

Example:
```c++
exporterOptions.convertAxis = "XyZ";
```

It seems to be fine in 3D Viewer of Microsoft Windows 10 and FBX Review of Autodesk.
However the animation curve seems to be shifted rotation-like in Blender - maybe it is an import issue of Blender or something which can be resolved by adjusting the import options a little bit.

Can you review if it helps with your issue, please?

**Comment by stonexing** [comment]
Great 👍.
Cannot wait to use you new code.
Let me try later.
