### ISSUE TITLE
Textures are not being exported

### ISSUE THREAD

**Issue by Danil0v3s** [Anohros/GrannyConverterLibrary#5]
Everything else works fine, except for the textures. It seems that if the `fbxexportmaterial.cpp` at L84 doesn't find the source texture it won't try to write. 

As we don't have the original texture in the filesystem but only the one embedded on the gr2 file, would it make sense to export directly from that?

**Comment by Anohros** [comment]
FYI: I have added an export for textures embedded in GR2 files. Now the embedded textures will be exported to separate PNG files in same folder of the exported FBX files. The implementation is already available in the main branch and with that I close the issue.
